### PR TITLE
X86 LTS

### PR DESCRIPTION
**Pull request by nickdesaulniers**
branched off of #40 . Let's see what's green for x86.

### CODE REVIEW

**Comment by nathanchance** [comment]
4.19 needs at least https://github.com/ClangBuiltLinux/linux/commit/81b45683487a51b0f4d3b29d37f20d6d078544e4 applied to it.

I'm looking into the 4.14 fail now.

**Comment by nickdesaulniers** [comment]
> I'm looking into the 4.14 fail now.

> FATAL: kernel too old

```
[   29.860060] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00007f00
[   29.860060] 
[   29.861196] CPU: 0 PID: 1 Comm: init Not tainted 4.14.80 #1
[   29.861710] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.11.1-1 04/01/2014
[   29.862527] Call Trace:
[   29.863291]  dump_stack+0xa6/0x100
[   29.863692]  panic+0xf4/0x2b0
[   29.863989]  ? do_exit+0x88f/0x910
[   29.864303]  do_exit+0x905/0x910
[   29.864688]  do_group_exit+0xc2/0xd0
[   29.865101]  SYSC_exit_group+0xb/0x10
[   29.865364]  SyS_exit_group+0x5/0x10
[   29.865575]  do_syscall_64+0x6a/0x80
[   29.865819]  entry_SYSCALL_64_after_hwframe+0x42/0xb7
[   29.866424] RIP: 0033:0x7f3ab2ff16a6
[   29.866687] RSP: 002b:00007fff08a33ee8 EFLAGS: 00000206 ORIG_RAX: 00000000000000e7
[   29.867305] RAX: ffffffffffffffda RBX: 00007f3ab2ff7088 RCX: 00007f3ab2ff16a6
[   29.867703] RDX: 000000000000007f RSI: 000000000000003c RDI: 000000000000007f
[   29.868160] RBP: 00007fff08a340d0 R08: 00000000000000e7 R09: 00007fff08a33e18
[   29.868558] R10: ffff8000f7528864 R11: 0000000000000206 R12: 00007fff08ad72dc
[   29.869074] R13: 0000000000000010 R14: 0000000000000000 R15: 00007f3ab3000190
[   29.870599] Kernel Offset: 0x1f000000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
[   29.871855] ---[ end Kernel panic - not syncing: Attempted to kill init! exitcode=0x00007f00
```


A passing x86_64 kernel has:
```
[   19.359141] Freeing unused kernel image memory: 2000K
[   19.366007] Freeing unused kernel image memory: 1920K
[   19.367007] rodata_test: all tests were successful
[   19.368651] Run /sbin/init as init process
[   19.795726] EXT4-fs (sda): re-mounted. Opts: (null)
[   19.892707] mkdir (1178) used greatest stack depth: 13072 bytes left
```

A failing 4.14 kernel has:
```
[   29.730921] Freeing unused kernel memory: 2000K
[   29.735362] Freeing unused kernel memory: 136K
[   29.736465] rodata_test: all tests were successful
FATAL: kernel too old
[   29.860060] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00007f00
<above panic>
```

4.4 and 4.9 have the same failures as arm.

**Comment by nickdesaulniers** [comment]
> FATAL: kernel too old

I wonder if glibc in our buildroot is failing to parse our kernel version string correctly?

Or it looks like our buildroot might need to have the correct headers: https://forums.xilinx.com/t5/Embedded-Linux/Linux-build-for-MicroZED-FATAL-kernel-too-old/td-p/812467

**Comment by nathanchance** [comment]
Yeah I think that's probably what it is because the default header value is 4.17. I've changed it to 4.4.

**Comment by nathanchance** [comment]
Thanks for the tip @nickdesaulniers!

`Linux version 4.14.80 (nathan@flashbox) (clang version 8.0.0-r346189 (https://github.com/nathanchance/clang 79a31f952e7f1c8f8977f896bffc4f080a764d0a) (https://git.llvm.org/git/llvm a8f890f4777f53bd9243bfdd9ed2b5d171cc8c03)) #1 SMP Mon Nov 12 19:20:17 MST 2018`

#56

**Comment by nickdesaulniers** [comment]
[build 269](https://travis-ci.com/ClangBuiltLinux/continuous-integration/builds/91178540) shows x86 4.14 passing.

[build 271](https://travis-ci.com/ClangBuiltLinux/continuous-integration/builds/91185339) shows x86 4.19.

**Comment by nathanchance** [comment]
https://github.com/nathanchance/continuous-integration/commit/72772017d2733738d59dad1b005336dc044dbf72

https://travis-ci.com/nathanchance/continuous-integration/jobs/158116418

**Comment by dileks** [comment]
On Tue, Nov 13, 2018 at 11:55 AM Nathan Chancellor <notifications@github.com>
wrote:

> nathanchance@7277201
> <https://github.com/nathanchance/continuous-integration/commit/72772017d2733738d59dad1b005336dc044dbf72>
>

I would keep the echo-line and do an "exit 0" instead in ...

Subject: [PATCH 1/2] DO-NOT-UPSTREAM: x86: Avoid warnings/errors due to lack
of asm goto

...
@echo Compiler lacks asm-goto support.
+ @exit 0
+KBUILD_CFLAGS += -D__BPF_TRACING__
...

- sed@ -

**Comment by nathanchance** [comment]
> I would keep the echo-line and do an "exit 0"

I'm curious, why? It doesn't avoid potential merge conflicts and we don't need to see that message every build since the whole reason the patch exists is because Clang doesn't support asm-goto.

**Comment by dileks** [comment]
On Tue, Nov 13, 2018 at 6:40 PM Nathan Chancellor <notifications@github.com>
wrote:

> I would keep the echo-line and do an "exit 0"
>
> I'm curious, why? It doesn't avoid potential merge conflicts and we don't
> need to see that message every build since the whole reason the patch
> exists is because Clang doesn't support asm-goto.
>
> I hope to see asm-goto support for clang-8, then I do not care :-).

- sed@ -

>

**Comment by nickdesaulniers** [comment]
ready for review.

**Comment by nickdesaulniers** [comment]
only cron jobs added. bypassing presubmit.

**Comment by nickdesaulniers** [comment]
> Also, we could enable 4.14 right now

done

**Pull request merged**
