### PR TITLE
remove 5.4 and 4.19 patch

### PR DESCRIPTION
**Pull request by nickdesaulniers**

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/builds/186168905

**Review by nathanchance — APPROVED** [review]
LGTM

**Review by msfjarvis — APPROVED** [review]

**Comment by nickdesaulniers** [comment]
I need to remove the patch from android-4.19-stable.

**Comment by nickdesaulniers** [comment]
(feel free to merge; don't wait for me to merge; you all are owners)

**Pull request merged**
