### PR TITLE
patches: llvm-12: Refresh x86_64 linux-next patch

### PR DESCRIPTION
**Pull request by nathanchance**
We get conflicts after
https://git.kernel.org/tip/597cfe48212a3f110ab0f918bf59791f453e65b7.

Presubmit: https://travis-ci.com/github/nathanchance/continuous-integration/builds/184073027

### CODE REVIEW

**Review by msfjarvis — APPROVED** [review]

**Comment by nickdesaulniers** [comment]
can you test dropping that patch? I don't think we should need it on next.  @nivedita76 landed a 6 patch series IIRC that addresses the assembler relaxation.  I still need to send that one liner patch to stable (based on this past week's meeting as suggested by @broonie and @arnd).

**Comment by nathanchance** [comment]
Sure. Are we just planning to have it go to stable only rather than mainline first? We have tried pinging the x86 maintainers several times at this point so I am not sure what else to do.

**Comment by nivedita76** [comment]
Pinged them again. It's also needed for v5.9.

There are also some trivial conflicts with the -stable trees, so we might need to send out separate patches that apply cleanly.

**Comment by nickdesaulniers** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?h=x86/urgent&id=09e43968db40c33a73e9ddbfd937f46d5c334924

**Review by nickdesaulniers — APPROVED** [review]
thanks! 🍹 🔐

**Pull request merged**
