### PR TITLE
Enable lld for ppc64

### PR DESCRIPTION
**Pull request by martell**

### CODE REVIEW

**Comment by shenki** [comment]
Blocked by:

- https://github.com/ClangBuiltLinux/linux/issues/253
- https://github.com/ClangBuiltLinux/linux/issues/303

**Comment by tpimh** [comment]
Now both issues are closed, let's try building again as soon as llvm binaries are updated!

**Comment by nickdesaulniers** [comment]
@martell do you mind rebasing your PR?  In fact, if LLD works then I recommend replacing the ld.bfd builds with ld.lld outright.

**Comment by martell** [comment]
@nickdesaulniers It seemingly works and boots the kernel and runs through which is great.

There are a couple of linker warnings to note

```sh
WARNING: vmlinux.o(.text+0x3328): Section mismatch in reference from the variable start_here_multiplatform to the function .init.text:early_setup()
The function start_here_multiplatform() references
the function __init early_setup().
This is often because start_here_multiplatform lacks a __init 
annotation or the annotation of early_setup is wrong.
WARNING: vmlinux.o(.text+0x3364): Section mismatch in reference from the variable start_here_common to the function .init.text:start_kernel()
The function start_here_common() references
the function __init start_kernel().
This is often because start_here_common lacks a __init 
annotation or the annotation of start_kernel is wrong.
WARNING: vmlinux.o(.text+0x7af38): Section mismatch in reference from the function remove_pmd_table() to the function .meminit.text:split_kernel_mapping()
The function remove_pmd_table() references
the function __meminit split_kernel_mapping().
This is often because remove_pmd_table lacks a __meminit 
annotation or the annotation of split_kernel_mapping is wrong.
  MODINFO modules.builtin.modinfo
ld.lld-9: warning: <internal>:(.bss.rel.ro) is being placed in '.bss.rel.ro'
ld.lld-9: warning: <internal>:(.symtab) is being placed in '.symtab'
ld.lld-9: warning: <internal>:(.symtab_shndx) is being placed in '.symtab_shndx'
ld.lld-9: warning: <internal>:(.shstrtab) is being placed in '.shstrtab'
ld.lld-9: warning: <internal>:(.strtab) is being placed in '.strtab'
  KSYM    .tmp_kallsyms1.o
ld.lld-9: warning: <internal>:(.bss.rel.ro) is being placed in '.bss.rel.ro'
ld.lld-9: warning: <internal>:(.symtab) is being placed in '.symtab'
ld.lld-9: warning: <internal>:(.symtab_shndx) is being placed in '.symtab_shndx'
ld.lld-9: warning: <internal>:(.shstrtab) is being placed in '.shstrtab'
ld.lld-9: warning: <internal>:(.strtab) is being placed in '.strtab'
  KSYM    .tmp_kallsyms2.o
  LD      vmlinux
ld.lld-9: warning: <internal>:(.bss.rel.ro) is being placed in '.bss.rel.ro'
ld.lld-9: warning: <internal>:(.symtab) is being placed in '.symtab'
ld.lld-9: warning: <internal>:(.symtab_shndx) is being placed in '.symtab_shndx'
ld.lld-9: warning: <internal>:(.shstrtab) is being placed in '.shstrtab'
ld.lld-9: warning: <internal>:(.strtab) is being placed in '.strtab'
```

```make
arch/powerpc/boot/main.c:107:18: warning: array comparison always evaluates to a constant [-Wtautological-compare]
        if (_initrd_end > _initrd_start) {
                        ^
1 warning generated.
```

Maybe we can catch this somewhere but this one seems unimportant


Last question, do we want to add lld to linux-next for ppc64? if not feel free to merge assuming all it okay. :)

**Comment by nathanchance** [comment]
> Maybe we can create an issue somewhere for this one but it seems unimportant for merging.

All of those should be tracked/answered already:

https://github.com/ClangBuiltLinux/linux/issues/212

https://github.com/ClangBuiltLinux/linux/issues/272

https://github.com/ClangBuiltLinux/linux/issues/273

https://github.com/ClangBuiltLinux/linux/issues/303#issuecomment-504723194

> Last question, do we want to add lld to linux-next for ppc64?
> If not feel free to merge assuming all it okay. :)

Yes, we should add it for linux-next as well if mainline is working fine.

**Comment by martell** [comment]
> Yes, we should add it for linux-next as well if mainline is working fine.
done

**Comment by nickdesaulniers** [comment]
🆒 😎

**Comment by tpimh** [comment]
Looking forward to other targets to move to LLD!

**Pull request merged**
