### PR TITLE
Reverts

### PR DESCRIPTION
**Pull request by nickdesaulniers**
https://github.com/ClangBuiltLinux/continuous-integration/issues/164
https://github.com/ClangBuiltLinux/linux/issues/480
https://github.com/ClangBuiltLinux/linux/issues/478

three separate commits so they can be reverted in the future

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
ah, I messed that up, 1 sec

**Comment by nathanchance** [comment]
Was about to comment but I figured you would notice shortly :P

**Comment by nickdesaulniers** [comment]
:hankey: I should have merged this yesterday!!! :argentina: 

Looks like some unrelated-to-clang breakage for ppc?

**Comment by nathanchance** [comment]
Yes, there was a missing patch in the security backports for powerpc: https://lore.kernel.org/stable/20190514201407.GA13424@archlinux-i9/

**Pull request merged**
