### PR TITLE
continuous-integration: Add allyesconfig

### PR DESCRIPTION
**Pull request by tapaswenipathak**
I mailed Travis about increasing the limit.

tl;dr this should close https://github.com/ClangBuiltLinux/continuous-integration/issues/27.

- [ ] @nathanchance comment
- [ ] Updates from Travis

### CODE REVIEW

**Comment by nathanchance** [comment]
`allyesconfig` is a build target, it should be called by `mako_reactor allyesconfig` here: https://github.com/ClangBuiltLinux/continuous-integration/blob/ded712131712186b766273eea1761ff18495217e/driver.sh#L250

arm64 (and maybe x86_64) on linux-next will be the only targets that build successfully with it though.

**Comment by tpimh** [comment]
Any progress on this one? There has been changes to the build system, this should be rebased.

**Comment by nathanchance** [comment]
I still do not believe this will be a good addition to our matrix. Our latest build took almost 9 hours to complete because more and more files get built with each kernel release. Adding allyesconfig to this will make it take significantly longer because we can only have three builds going at a time. For that matter, we only get 180 minutes maximum per job and an x86 allyesconfig build on a four core machine ([Packet's t1.small.x86](https://www.packet.com/cloud/servers/t1-small/)) with LLVM 10 on Ubuntu 18.04 takes around 5 hours and requires at least 8GB of disk space for the kernel source and resulting files (we only get two cores and 18GB of disk space). I don't think Travis will be able to handle this.

**Comment by tpimh** [comment]
Maybe changes should be made only to driver.sh and not affect our travis matrix. I would suggest introducing `CONFIG` variable which can be specified like `REPO`. If unspecified, the same old set of defconfigs is used, if set to "allyesconfig", builds allyesconfig. So it would be extremely easy to test locally by just running `./driver.sh CONFIG=allyesconfig` and waiting for a while.

**Comment by nathanchance** [comment]
Yes that would be okay. We could also come up with a list of common configs that tend to stress issues in LLVM/Clang and build with those (some immediate ones are CONFIG_RANDOMIZE_BASE and CONFIG_KASAN).

**Pull request closed without merging**
