### PR TITLE
driver: Enable llvm-objcopy and llvm-strip

### PR DESCRIPTION
**Pull request by nathanchance**
except for s390, which does not appear to have any support for it in
the LLVM tools.

Tested locally with build-all.sh.

Closes: https://github.com/ClangBuiltLinux/continuous-integration/pull/212
Closes: https://github.com/ClangBuiltLinux/continuous-integration/issues/249

### CODE REVIEW

**Comment by tpimh** [comment]
For s390 you set `OBJDUMP` variable, not `STRIP`. Is it intentional?

**Comment by nathanchance** [comment]
Yes and no. I intentionally left it out because it does not appear to be used during a build (I have not seen an error). I can add it if you feel it necessary.

**Comment by tpimh** [comment]
If it's not used during the build, no need to add it. I was just concerned because this pull request doesn't mention objdump anywhere else.

**Comment by nathanchance** [comment]
Ah, gotcha. The objdump one is https://github.com/ClangBuiltLinux/linux/issues/859 and it has been there since we added s390 support.

**Comment by nathanchance** [comment]
> cool, so we'll still need to turn this on in the travis yaml?

Nope, it is enabled by default now.

> Basically, it's a vote against supporting older versions.

Sure, I can push a patch after I merge this.

**Comment by nickdesaulniers** [comment]
> Nope, it is enabled by default now.

*rereads code*

got it, just not s390, I see.

**Pull request merged**
