### PR TITLE
add facility to apply patches to all branches.

### PR DESCRIPTION
**Pull request by nickdesaulniers**
This probably wont get used too often, as patches probably wont apply
cleanly across all these different branches, but makes it simple to
apply patches to many trees.

Also, add patch for
https://github.com/ClangBuiltLinux/linux/issues/416

### CODE REVIEW

**Comment by nathanchance** [comment]
I would also presubmit one architecture on each different repo/branch combo that we support, just to make sure the patch applied (I've tested arm64 on common 4.9 and stable 4.4).

**Comment by nickdesaulniers** [comment]
odd, @nathanchance any idea why the build is stopping after applying the patches? Seems like the last output is `+ [[ -d ../patches/linux/arm ]]`.

**Comment by nickdesaulniers** [comment]
https://stackoverflow.com/a/17336953/1027966:
```
The default return value is the exit value of the last statement executed within the function.
```
so I probably need an explicit `return 0` in there.

**Comment by nathanchance** [comment]
I would do an `if else` with an explicit return zero in the else case, otherwise we won't capture the git apply error code.

**Comment by nickdesaulniers** [comment]
green presubmit showing patch applies to each branch: https://travis-ci.com/ClangBuiltLinux/continuous-integration/builds/104603172

**Pull request merged**
