### PR TITLE
Revert "travis: Disable ppc32 for now"

### PR DESCRIPTION
**Pull request by nickdesaulniers**
This reverts commit cfc8c91e31cedbaa0097ec3728a8b289ee5bace6.

https://github.com/ClangBuiltLinux/linux/issues/1044

https://reviews.llvm.org/D81767

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
> until that commit hits apt.llvm.org

Is there a way to check that?

**Comment by nathanchance** [comment]
> > until that commit hits apt.llvm.org
> 
> 
> 
> Is there a way to check that?

The commit hash is included in the package version, which can be seen when the package is installed from the Travis log: https://travis-ci.com/github/ClangBuiltLinux/dockerimage/jobs/349518668

Looks like https://github.com/llvm/llvm-project/commit/837ca479606 is the current commit, which doesn’t include the commit to fix this.

**Comment by nickdesaulniers** [comment]
cool, thanks, so [last night's docker image](https://travis-ci.com/github/ClangBuiltLinux/dockerimage/jobs/350215460) was https://github.com/llvm/llvm-project/commit/56262a74c31 which should contain https://github.com/llvm/llvm-project/commit/2d8e105db6bea10a6b96e4a094e73a87987ef909.

**Comment by nathanchance** [comment]
Booting will still be broken due to https://lore.kernel.org/linuxppc-dev/20200616002720.GA1307277@ubuntu-n2-xlarge-x86/ but I'll push a fix for here and boot-utils in a sec once I test.

**Pull request merged**
